name: climetlab_s2s_ai_competition installs

on: pull_request

jobs:
  install-climetlab_s2s_ai_competition:  # Installs climetlab_s2s_ai_competition on various OS.
    name: Install climetlab_s2s_ai_competition, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: import climetlab_s2s_ai_competition
      run: |
        python -c "import climetlab_s2s_ai_competition"

  install-conda-climetlab_s2s_ai_competition:
    name: install-conda-climetlab_s2s_ai_competition
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
    - name: Set up conda environment
      run: |
          conda create --name climetlab_s2s_ai_competition-dev python=3.7 xarray
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: import climetlab_s2s_ai_competition
      run: |
        python -c "import climetlab_s2s_ai_competition"
